// src/constants/cities.js
export const ethiopianCities = [
  { label: "Addis Ababa", value: "Addis Ababa" },
  { label: "Dire Dawa", value: "Dire Dawa" },
  { label: "Mekelle", value: "Mekelle" },
  { label: "Adama", value: "Adama" },
  { label: "Bahir Dar", value: "Bahir Dar" },
  { label: "Gondar", value: "Gondar" },
  { label: "Hawassa", value: "Hawassa" },
  { label: "Jimma", value: "Jimma" },
  { label: "Jijiga", value: "Jijiga" },
  { label: "Dessie", value: "Dessie" },
  { label: "Harar", value: "Harar" },
  { label: "Shashamane", value: "Shashamane" },
  { label: "Arba Minch", value: "Arba Minch" },
  { label: "Sodo", value: "Sodo" },
  { label: "Nekemte", value: "Nekemte" },
  { label: "Debre Markos", value: "Debre Markos" },
  { label: "Debre Birhan", value: "Debre Birhan" },
  { label: "Asella", value: "Asella" },
  { label: "Weldiya", value: "Weldiya" },
  { label: "Sebeta", value: "Sebeta" },
  { label: "Kombolcha", value: "Kombolcha" },
  { label: "Ambo", value: "Ambo" },
  { label: "Bishoftu", value: "Bishoftu" },
  { label: "Hossana", value: "Hossana" },
  { label: "Gambela", value: "Gambela" },
  { label: "Assosa", value: "Assosa" },
  { label: "Semera", value: "Semera" },
  { label: "Negele Boran", value: "Negele Boran" },
  { label: "Dilla", value: "Dilla" },
  { label: "Bale Robe", value: "Bale Robe" },
  { label: "Fiche", value: "Fiche" },
  { label: "Metu", value: "Metu" },
  { label: "Dembi Dolo", value: "Dembi Dolo" },
  { label: "Gode", value: "Gode" },
  { label: "Jinka", value: "Jinka" },
  { label: "Dangila", value: "Dangila" },
  { label: "Wolaita Sodo", value: "Wolaita Sodo" },
  { label: "Bedele", value: "Bedele" },
  { label: "Adigrat", value: "Adigrat" },
  { label: "Axum", value: "Axum" },
  { label: "Lalibela", value: "Lalibela" },
  { label: "Goba", value: "Goba" },
  { label: "Dukem", value: "Dukem" },
  { label: "Butajira", value: "Butajira" },
  { label: "Yabelo", value: "Yabelo" },
  { label: "Finote Selam", value: "Finote Selam" },
  { label: "Mizan Teferi", value: "Mizan Teferi" },
  { label: "Burayu", value: "Burayu" },
  { label: "Areka", value: "Areka" },
  { label: "Welkite", value: "Welkite" },
  { label: "Awasa", value: "Awasa" }, // Alternate spelling for Hawassa
];
